name: Result Check

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:

  checker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install firebase-admin@11.11.1 axios

      - name: Create Firebase Key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > serviceAccount.json
          if [ ! -s serviceAccount.json ]; then echo "Erro: serviceAccount.json está vazio" && exit 1; fi

      - name: Run Result Checker
        env:
         API_KEY_1: ${{ secrets.TWELVEDATA_KEY }}
         API_KEY_2: ${{ secrets.TWELVEDATA_KEY_2 }}
         API_KEY_3: ${{ secrets.TWELVEDATA_KEY_3 }}
        run: |
          node js/checker.js
